baseurl: /cs224w-notes
title: Course on machine learning with graphs
subtitle: Lecture notes for Stanford CS 224W.
author: Manan Shah
simple_search: http://google.com/search
description: LLecture notes for Stanford CS 224W.
name: cs224w-notes
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink: /articles/:short_year/:title
timezone: America/New_York
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: gvim
git:
  branch: master
transfer:
  command: rsync
  settings: -av
  source: _site/
